on:
  workflow_dispatch
        
jobs:
  deploy-book:
      runs-on: ubuntu-latest
      steps:  
      - name: Echo Var
        run: echo "Testing...with python version ${{ inputs.python-version }}"
