on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.6', '3.8', 3.9']
    uses: TheRealZoidberg/called_test/.github/workflows/called.yml@main 
    with:
      python-version: ${{ matrix.python-version'
        




