on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

  runMatrix:
    needs: build
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            notebooks: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
      - name: call it
        uses: TheRealZoidberg/called_test/.github/workflows/called.yml@main 
        




